### ISSUE TITLE
Error in run_app() : could not find function "run_app"

### ISSUE THREAD

**Issue by emawbgit** [lsms-worldbank/cleanstart#4]
![image](https://github.com/lsms-worldbank/cleanstart/assets/65594313/f6741b3c-a5a0-4200-b8ad-81c587129564)

Sorry Arthur, unfortunately I am getting this error - any insight on this?

**Comment by arthur-shaw** [comment]
@emawbgit,  so sorry I missed the notification for this issue. While fixing another issue today, I updated the documentation on how to run the app. The package needs to be loaded before the app it contains can be run. Silly oversight on my part. Sorry again.

**Comment by arthur-shaw** [comment]
Closed in 5ed23b7ffeb59d24645c901c23fe03970a6fa9e9
